(function attachCommonData(global) {
  const data = {
    MAX_VISIBLE_RECORDS: 20,
    DEFAULT_LOGIN_IDENTIFIER: "2022667789",
    SIDEBAR_FIRST_OPEN_PREFIX: "sgoa-sidebar-first-open",
    BLOCKED_VIEWS: new Set(["participante", "gerenciar"]),
    VIEW_LABELS: {
      home: "Informações Gerais",
      "pesquisa-geral": "Pesquisa Geral",
      participante: "Área do Participante",
      gerenciar: "Gerenciar Oficinas",
      oficinas: "Oficinas Cadastradas",
      identificacao: "Identificação",
    },
    DEFAULT_PARTICIPANT: {
      identifier: "1145",
      firstAccessDate: "21/03/2026",
      lastAccessDateTime: "21/03/2026 - 23:31",
    },
    TOAST_MESSAGES: {
      blockedAccess: {
        title: "Ação interrompida:",
        message: "É necessário validar as suas credenciais de acesso principal antes de visualizar esta área.",
      },
      participantOperation: {
        title: "Não Realizado:",
        message: "SYS-OP-004 - Falha na execução da operação solicitada.",
      },
    },
    MOCK_WORKSHOPS: [
      {
        cod: "ELM-1701",
        title: "Leitura de Diagramas Elétricos Industriais",
        period: "02/04 a 12/04",
        status: "Aberta",
        modality: "Presencial",
        hours: "12 Hrs",
        description: "Interpretação de esquemas elétricos e identificação de componentes em circuitos industriais.",
      },
      {
        cod: "ELM-1702",
        title: "Montagem de Painéis de Controle",
        period: "05/04 a 25/04",
        status: "Aberta",
        modality: "Presencial",
        hours: "24 Hrs",
        description: "Organização, fixação e ligação de dispositivos em painéis de comando eletromecânicos.",
      },
      {
        cod: "ELM-1703",
        title: "Sensores e Atuadores Industriais",
        period: "08/04 a 18/04",
        status: "Fechada",
        modality: "EaD",
        hours: "10 Hrs",
        description: "Funcionamento e aplicação de sensores e atuadores em sistemas automatizados.",
      },
      {
        cod: "ELM-1704",
        title: "Manutenção de Motores Elétricos",
        period: "10/04 a 28/04",
        status: "Aberta",
        modality: "Presencial",
        hours: "20 Hrs",
        description: "Procedimentos básicos de manutenção, testes e diagnóstico de falhas em motores.",
      },
      {
        cod: "ELM-1705",
        title: "Comandos Eletropneumáticos",
        period: "12/04 a 03/05",
        status: "Aberta",
        modality: "EaD",
        hours: "30 Hrs",
        description: "Integração entre circuitos elétricos e sistemas pneumáticos para automação.",
      },
      {
        cod: "ELM-1706",
        title: "Metrologia Mecânica Básica",
        period: "15/04 a 25/04",
        status: "Fechada",
        modality: "Presencial",
        hours: "14 Hrs",
        description: "Uso de instrumentos de medição aplicados à mecânica industrial.",
      },
      {
        cod: "ELM-1707",
        title: "Inversores de Frequência na Prática",
        period: "18/04 a 08/05",
        status: "Aberta",
        modality: "EaD",
        hours: "18 Hrs",
        description: "Configuração e operação de inversores para controle de velocidade de motores.",
      },
      {
        cod: "ELM-1708",
        title: "Transmissões Mecânicas Industriais",
        period: "20/04 a 10/05",
        status: "Fechada",
        modality: "Presencial",
        hours: "20 Hrs",
        description: "Estudo de engrenagens, correias e sistemas de transmissão de movimento.",
      },
      {
        cod: "ELM-1709",
        title: "Lubrificação Industrial",
        period: "22/04 a 30/04",
        status: "Aberta",
        modality: "EaD",
        hours: "8 Hrs",
        description: "Técnicas de lubrificação e prevenção de desgaste em equipamentos.",
      },
      {
        cod: "ELM-1710",
        title: "Alinhamento de Eixos e Acoplamentos",
        period: "25/04 a 15/05",
        status: "Fechada",
        modality: "Presencial",
        hours: "16 Hrs",
        description: "Ajuste e alinhamento de conjuntos rotativos para evitar falhas mecânicas.",
      },
      {
        cod: "ELM-1711",
        title: "Partida de Motores Trifásicos",
        period: "28/04 a 18/05",
        status: "Aberta",
        modality: "EaD",
        hours: "22 Hrs",
        description: "Aplicação de diferentes métodos de partida para motores industriais.",
      },
      {
        cod: "ELM-1712",
        title: "Soldagem Aplicada à Manutenção",
        period: "30/04 a 20/05",
        status: "Aberta",
        modality: "Presencial",
        hours: "18 Hrs",
        description: "Noções práticas de soldagem voltadas à manutenção mecânica.",
      },
      {
        cod: "ELM-1713",
        title: "Hidráulica Industrial",
        period: "03/05 a 23/05",
        status: "Aberta",
        modality: "EaD",
        hours: "32 Hrs",
        description: "Fundamentos de sistemas hidráulicos e seus componentes.",
      },
      {
        cod: "ELM-1714",
        title: "CLP com Diagnóstico de Falhas",
        period: "05/05 a 02/06",
        status: "Fechada",
        modality: "EaD",
        hours: "36 Hrs",
        description: "Programação e análise de falhas em sistemas automatizados com CLP.",
      },
      {
        cod: "ELM-1715",
        title: "Chaves Fim de Curso e Sensoriamento",
        period: "08/05 a 18/05",
        status: "Aberta",
        modality: "Presencial",
        hours: "10 Hrs",
        description: "Aplicação de dispositivos de posição em automação industrial.",
      },
      {
        cod: "ELM-1716",
        title: "Manutenção de Bombas Industriais",
        period: "10/05 a 30/05",
        status: "Fechada",
        modality: "Presencial",
        hours: "20 Hrs",
        description: "Diagnóstico e manutenção básica de bombas centrífugas.",
      },
      {
        cod: "ELM-1717",
        title: "Instrumentação Industrial Básica",
        period: "12/05 a 25/05",
        status: "Aberta",
        modality: "EaD",
        hours: "14 Hrs",
        description: "Medição de variáveis como pressão, temperatura e nível.",
      },
      {
        cod: "ELM-1718",
        title: "Fixação Mecânica e Torque",
        period: "15/05 a 25/05",
        status: "Aberta",
        modality: "Presencial",
        hours: "12 Hrs",
        description: "Aplicação correta de fixadores e técnicas de torqueamento.",
      },
      {
        cod: "ELM-1719",
        title: "Diagnóstico de Sistemas Eletromecânicos",
        period: "18/05 a 08/06",
        status: "Fechada",
        modality: "EaD",
        hours: "28 Hrs",
        description: "Identificação de falhas em sistemas integrados elétricos e mecânicos.",
      },
      {
        cod: "ELM-1720",
        title: "Manutenção Preditiva Industrial",
        period: "20/05 a 10/06",
        status: "Aberta",
        modality: "EaD",
        hours: "16 Hrs",
        description: "Monitoramento de equipamentos para prevenção de falhas.",
      },
    ],
  };

  global.SGOAData = data;
}(window));
