(function attachCommonData(global) {
  const data = {
    MAX_VISIBLE_RECORDS: 20,
    DEFAULT_LOGIN_IDENTIFIER: "2022667789",
    SIDEBAR_FIRST_OPEN_PREFIX: "sgoa-sidebar-first-open",
    BLOCKED_VIEWS: new Set(["participante", "gerenciar"]),
    VIEW_LABELS: {
      home: "Informações Gerais",
      "pesquisa-geral": "Pesquisa Geral",
      "pesquisa-detalhes": "Consulta Detalhada",
      participante: "Área do Participante",
      gerenciar: "Gerenciar Oficinas",
      oficinas: "Oficinas Cadastradas",
      identificacao: "Identificação",
    },
    DEFAULT_PARTICIPANT: {
      identifier: "1145",
      firstAccessDate: "21/03/2026",
      lastAccessDateTime: "21/03/2026 - 23:31",
    },
    TOAST_MESSAGES: {
      blockedAccess: {
        title: "Ação interrompida:",
        message: "É necessário validar as suas credenciais de acesso principal antes de visualizar esta área.",
      },
      participantOperation: {
        title: "Não Realizado:",
        message: "SYS-OP-004 - Falha na execução da operação solicitada.",
      },
    },
    MOCK_WORKSHOPS: [
      // DUPLICADAS (8 pares)

      {
        cod: "ELM-1801",
        title: "Leitura de Diagramas Elétricos Industriais",
        period: "01/02 a 10/02",
        status: "Fechada",
        modality: "Presencial",
        hours: "12 Hrs",
        description: "Interpretação de esquemas elétricos e identificação de componentes em circuitos industriais.",
      },
      {
        cod: "ELM-1802",
        title: "Leitura de Diagramas Elétricos Industriais",
        period: "02/04 a 12/04",
        status: "Aberta",
        modality: "Presencial",
        hours: "12 Hrs",
        description: "Interpretação de esquemas elétricos e identificação de componentes em circuitos industriais.",
      },

      {
        cod: "ELM-1803",
        title: "Montagem de Painéis de Controle",
        period: "10/02 a 28/02",
        status: "Fechada",
        modality: "Presencial",
        hours: "24 Hrs",
        description: "Organização, fixação e ligação de dispositivos em painéis de comando eletromecânicos.",
      },
      {
        cod: "ELM-1804",
        title: "Montagem de Painéis de Controle",
        period: "05/04 a 25/04",
        status: "Aberta",
        modality: "Presencial",
        hours: "24 Hrs",
        description: "Organização, fixação e ligação de dispositivos em painéis de comando eletromecânicos.",
      },

      {
        cod: "ELM-1805",
        title: "Sensores e Atuadores Industriais",
        period: "15/02 a 25/02",
        status: "Fechada",
        modality: "EaD",
        hours: "10 Hrs",
        description: "Funcionamento e aplicação de sensores e atuadores em sistemas automatizados.",
      },
      {
        cod: "ELM-1806",
        title: "Sensores e Atuadores Industriais",
        period: "08/04 a 18/04",
        status: "Aberta",
        modality: "EaD",
        hours: "10 Hrs",
        description: "Funcionamento e aplicação de sensores e atuadores em sistemas automatizados.",
      },

      {
        cod: "ELM-1807",
        title: "Manutenção de Motores Elétricos",
        period: "20/02 a 10/03",
        status: "Fechada",
        modality: "Presencial",
        hours: "20 Hrs",
        description: "Procedimentos básicos de manutenção, testes e diagnóstico de falhas em motores.",
      },
      {
        cod: "ELM-1808",
        title: "Manutenção de Motores Elétricos",
        period: "10/04 a 28/04",
        status: "Aberta",
        modality: "Presencial",
        hours: "20 Hrs",
        description: "Procedimentos básicos de manutenção, testes e diagnóstico de falhas em motores.",
      },

      {
        cod: "ELM-1809",
        title: "Inversores de Frequência na Prática",
        period: "05/03 a 20/03",
        status: "Fechada",
        modality: "EaD",
        hours: "18 Hrs",
        description: "Configuração e operação de inversores para controle de velocidade de motores.",
      },
      {
        cod: "ELM-1810",
        title: "Inversores de Frequência na Prática",
        period: "18/04 a 08/05",
        status: "Aberta",
        modality: "EaD",
        hours: "18 Hrs",
        description: "Configuração e operação de inversores para controle de velocidade de motores.",
      },

      {
        cod: "ELM-1811",
        title: "Transmissões Mecânicas Industriais",
        period: "10/03 a 25/03",
        status: "Fechada",
        modality: "Presencial",
        hours: "20 Hrs",
        description: "Estudo de engrenagens, correias e sistemas de transmissão de movimento.",
      },
      {
        cod: "ELM-1812",
        title: "Transmissões Mecânicas Industriais",
        period: "20/04 a 10/05",
        status: "Aberta",
        modality: "Presencial",
        hours: "20 Hrs",
        description: "Estudo de engrenagens, correias e sistemas de transmissão de movimento.",
      },

      {
        cod: "ELM-1813",
        title: "Lubrificação Industrial",
        period: "12/03 a 18/03",
        status: "Fechada",
        modality: "EaD",
        hours: "8 Hrs",
        description: "Técnicas de lubrificação e prevenção de desgaste em equipamentos.",
      },
      {
        cod: "ELM-1814",
        title: "Lubrificação Industrial",
        period: "22/04 a 30/04",
        status: "Aberta",
        modality: "EaD",
        hours: "8 Hrs",
        description: "Técnicas de lubrificação e prevenção de desgaste em equipamentos.",
      },

      {
        cod: "ELM-1815",
        title: "Hidráulica Industrial",
        period: "15/03 a 05/04",
        status: "Fechada",
        modality: "EaD",
        hours: "32 Hrs",
        description: "Fundamentos de sistemas hidráulicos e seus componentes.",
      },
      {
        cod: "ELM-1816",
        title: "Hidráulica Industrial",
        period: "03/05 a 23/05",
        status: "Aberta",
        modality: "EaD",
        hours: "32 Hrs",
        description: "Fundamentos de sistemas hidráulicos e seus componentes.",
      },

      // RESTANTE (únicas)

      {
        cod: "ELM-1817",
        title: "CLP com Diagnóstico de Falhas",
        period: "05/05 a 02/06",
        status: "Fechada",
        modality: "EaD",
        hours: "36 Hrs",
        description: "Programação e análise de falhas em sistemas automatizados com CLP.",
      },
      {
        cod: "ELM-1818",
        title: "Chaves Fim de Curso e Sensoriamento",
        period: "08/05 a 18/05",
        status: "Aberta",
        modality: "Presencial",
        hours: "10 Hrs",
        description: "Aplicação de dispositivos de posição em automação industrial.",
      },
      {
        cod: "ELM-1819",
        title: "Diagnóstico de Sistemas Eletromecânicos",
        period: "18/05 a 08/06",
        status: "Fechada",
        modality: "EaD",
        hours: "28 Hrs",
        description: "Identificação de falhas em sistemas integrados elétricos e mecânicos.",
      },
      {
        cod: "ELM-1820",
        title: "Manutenção Preditiva Industrial",
        period: "20/05 a 10/06",
        status: "Aberta",
        modality: "EaD",
        hours: "16 Hrs",
        description: "Monitoramento de equipamentos para prevenção de falhas.",
      },
    ],
  };

  global.SGOAData = data;
}(window));
